### ISSUE TITLE
Processing 2.1.1 is incompatible with Java 10

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars-lab#66]
* Code is relying on processing 2.1.1 and incompatible with processing 3.x.x
* processing 2.1.1 crashes in a Java 10 Environment

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.opennars.lab.microworld.Pong.<init>(Pong.java:47)
	at org.opennars.lab.microworld.Pong.main(Pong.java:1336)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3107)
	at java.base/java.lang.String.substring(String.java:1873)
	at processing.core.PApplet.<clinit>(PApplet.java:182)
	... 2 more

**Comment by patham9** [comment]
If someone is motivated to change the dependency and test the existing examples in Launcher with the new processing, we can move to 3.x.x. But don't waste your time, core is more important.
