### ISSUE TITLE
Potential issues in bin_lab in v3.0.4 release

### ISSUE THREAD

**Issue by digikar99** [opennars/opennars-lab#90]
I'm not sure if I am misunderstanding the button icons, but I'm expecting the '▶' to correspond to the play button, which also changes to the pause button '⏸'. However, while running the ... the button seems to have no effect.

Windows -> Concept Network shows the concept network, but changing 'Concepts' to 'Inheritance' or 'Implication' from the drop-down list in the top-left corner stops the simulation. In the terminal, I see the following exception:

```
Exception in thread "Animation Thread" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at org.opennars.io.events.EventEmitter.emit(EventEmitter.java:134)
	at org.opennars.main.Nar.emit(Nar.java:650)
	at org.opennars.main.Nar.cycles(Nar.java:625)
	at org.opennars.lab.microworld.SimNAR$MyPapplet$Hai.UpdateSOM(SimNAR.java:442)
	at org.opennars.lab.microworld.SimNAR$MyPapplet.hsim_ObjectTask(SimNAR.java:576)
	at org.opennars.lab.microworld.SimNAR$MyPapplet$Hsim.Simulate(SimNAR.java:807)
	at org.opennars.lab.microworld.SimNAR$MyPapplet$Hamlib.Simulate(SimNAR.java:1035)
	at org.opennars.lab.microworld.SimNAR$MyPapplet$Hamlib.Update(SimNAR.java:1023)
	at org.opennars.lab.microworld.SimNAR$MyPapplet.draw(SimNAR.java:1514)
	at processing.core.PApplet.handleDraw(PApplet.java:2386)
	at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
	at processing.core.PApplet.run(PApplet.java:2256)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The above exception occured on Java 11. On Java 8, there is no exception, but the window freezes.

**Comment by patham9** [comment]
JVM isn't fully backward compatible due to some native OpenGL dependencies used by the Processing library. The .jar was built for JDK 8. Please use older JDK versions in case you need the concept graph to work, I remember new JDK's (close to 20) are throwing some exceptions, but JDK 10, 11, or 12 might work without error.
